### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by ptcmariano** [Ardobras/mysql-to-rest#5]
in 30 seconds after a request stops the server with error:
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (...\mysql-to-rest\node_modules\mysql\lib\protocol\Protocol.js:109:13)
    at Socket.<anonymous> (...\mysql-to-rest\node_modules\mysql\lib\Connection.js:102:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

can help me?

**Comment by kenodressel** [comment]
Well it looks like you have an issue with the db connection. This is an error that comes from the mysql package: "Connection lost: The server closed the connection."

**Comment by ptcmariano** [comment]
I was using createConnection

 `var connection = mysql.createConnection({`

And to not timeout crash the api, use

 `var connection = mysql.createPool({`
